Milestone: Add Form
Lancelot-SO/blogger pull request #7
Opened 2023-05-11 14:14 UTC by Lancelot-SO

### The following updates were made:

- Created a method called current_user in my ApplicationController to make current user data available to all controllers.
- It will return the first user from the database.
- Created forms to perform the following functions:
- Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
- Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
- Modified readme file
- Linters setup correctly

2023-05-11 16:00 UTC, BenMukebo requested changes
### Hi @Lancelot-SO,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Gitflow was correctly used.  ✔️   
- ApplicationController contains `#current_user` method ✔️ 
- There a pair of routes in the routes.rb file ✔️ 
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 16:00 UTC, BenMukebo commented on app/controllers/comments_controller.rb
> +    @comment.author = @user
- [ ] Great job so far 👏🏻 However, a comment should be created on behalf of the currently logged-in user (current_user) of the app. Kindly address this. 💯 👍🏻 The comments  create action may look similar to the one shown below:

```ruby
 def create
    @post = Post.find(params[:post_id])
    @comment = @current_user.comments.new(params)
    @comment.post_id = @post.id

    ...
  end
```

2023-05-11 16:00 UTC, BenMukebo commented on app/views/comments/_form.html.erb
> +<%= form_with model:[@current_user, @post, Comment.new], url:user_post_comments_path(@current_user, @post) do |form| %>
- [ ] Kindly as done on the Post, there should be a form in the views/comments/new.html.erb file which accepts input for creating comments. let's create this 👍🏻

2023-05-11 16:03 UTC, BenMukebo commented on app/controllers/posts_controller.rb
> +    else
- [OPTIONAL] It will be better much better to redirect the user to the Post page `@post ` instead of the current_user profile page. 👍🏻

2023-05-12 09:41 UTC, Lancelot-SO commented on app/controllers/comments_controller.rb
> +    @comment.author = @user
Thanks for your request. I have fixed it 🤞

2023-05-12 10:00 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @Lancelot-SO, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well to implement the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 10:11 UTC, merged